spring.application.name=oauth-cliente

server.port=8090

spring.security.user.name=user
spring.security.user.password=123456
spring.security.user.roles=ADMIN


spring.security.oauth2.client.registration.github.client-id=Ov23liJZf4sBd8hRkiC7
spring.security.oauth2.client.registration.github.client-secret=f0c27e8f9001aed47448c86fe859c5d07dcb193a
spring.security.oauth2.client.registration.github.scope=read:user,repo

# github - settings -> developer settings -> OAuth Apps -> New OAuth App
